version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: tina_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: tina
      MONGO_INITDB_ROOT_PASSWORD: tina_password
volumes:
  mongo_data:
